name = "UdyrSMP"
author = "AmeMeida, Frais"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "015fbc2d61f9da5ae0b31c35703ed3e555b882e79b33b97763eb72d79152c5ea"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
